### ISSUE TITLE
Comentarios QMP2

### ISSUE THREAD

**Issue by ggallici** [ailengonzalezperez/DDS-QMP-I1#1]
Buenas, antes que nada perdón por la demora. Te voy marcando un par de cositas fuí viendo en tu solución:

- En el diagrama de clases usá las flechas que utilizamos en clase (ojo con esto porque puede descontar puntos en el parcial).
- Sobre las validaciones de la prenda:
    1. Lo más importante es que esas validaciones estén en el Borrador, para desacoplar la lógica creacional de la Prenda (y de yapa sacas algo de lógica repetida).
    2. No hace falta que tengas 2 constructores, simplemente podes no validar el color y listo, ya es opcional :D.
    3. https://github.com/ailengonzalezperez/DDS-QueMePongo/blob/e28db0cdd2ee72492847534c68f5ea0f2ff0bb08/queMePongo.java#L14-L16
Acá no es necesaria ésta validación dado que ni siquiera deberías recibir la categoría por constructor (simplemente recibís el tipo que ya tiene su categoria válida).
    4. Hay algunas validaciones de material & trama que no tienen mucho sentido, para esos casos con evitar que lleguen nulls nos alcanza. Algo más interesante que podrías hacer es validar cada dependencia de la prenda por separado (en el borrador) para que al momento de fallar sepamos exactamente cuál configuración era la invalida.

**Comment by ailengonzalezperez** [comment]
Gracias por la devolución! 
- Cambié la herramienta con la que hacía los diagramas para QMP4 para que estén mejor.
- Los otros puntos con lo que vimos en clase me quedaron mucho más claros. Lo de material y trama me había confundido bastante.
